services:
  - type: web
    name: backround-remover
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: REMBG_MODEL
        value: u2netp
